version: '3.5'

services:
  php:
    container_name: php
    build:
      context: ./docker/build
      dockerfile: php.Dockerfile
    volumes:
       - "./htdocs:/var/www"
  nginx:
     image: nginx:latest
     container_name: nginx
     volumes:
       - "./docker/config/nginx/conf.d:/etc/nginx/conf.d"
       - "./htdocs:/var/www"
     ports:
       - "80:80"

  mysql:
     image: mysql:8.0
     container_name: mysql
     command: --default-authentication-plugin=mysql_native_password
     cap_add:
       - SYS_NICE
     environment:
       MYSQL_ALLOW_EMPTY_PASSWORD: "false"
       MYSQL_ROOT_PASSWORD: "root"
     volumes:
       - "./data/mysql:/var/lib/mysql"
       - "./data/dump:/docker-entrypoint-initdb.d/:ro"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root